### ISSUE TITLE
Repetitive output on first-timer "nb commit" 

### ISSUE THREAD

**Issue by travenasty** [northbrookjs/northbrook#11] opened 2016-08-20 22:56 UTC
**Code to reproduce the issue:**

```
hz init gold
cd gold
nb init
git add README.md
nb commit
```

<img width="472" alt="screen shot 2016-08-20 at 16 49 29" src="https://cloud.githubusercontent.com/assets/370488/17834289/b3467064-66f6-11e6-89a5-68afa056f08c.png">

**Expected behavior:**

Single command line prompt with multiple choice options.

**Actual behavior:**

Repeated (3x) blocks of command line instructions. [screenshot below]

<img width="760" alt="screen shot 2016-08-20 at 16 49 53" src="https://cloud.githubusercontent.com/assets/370488/17834297/f6e62508-66f6-11e6-9551-788bfcd275a7.png">

**Versions of packages used:**

cz-cli@0.0.0, northbrook@1.2.0

tried on Node v6.2.2 and v6.4.0

**Comment by TylorS** [comment] 2016-08-21 02:20
Thanks for the bug report. I will investigate it ASAP!

**Comment by TylorS** [comment] 2016-08-21 09:18
Can I further ask which OS you're using?

**Comment by travenasty** [comment] 2016-08-21 16:07
Sorry I forgot to include it originally:  OS X El Capitan 10.11.6
I don't know if it makes any difference, but I use nvm to manage Node:

```
which node
/Users/trave/.nvm/versions/node/v6.2.2/bin/node
```

With a little direction... I'm open to forking and running Northbrook from source, and adding debug statements where helpful.

**Comment by TylorS** [comment] 2016-08-21 21:03
Thank you very much. Ive been developing this on Ubuntu 16.04. I don't get the repeated output unfortunately. I will try to figure out the best way to solve this, and I appreciate your help in doing so. Also, thank you for trying this out, I really want to make this great and useful for everyone.

**Comment by TylorS** [comment] 2016-08-22 23:03
@travenasty I'm working on rewriting the internals to be unit-testable. I'm also trying to remove a lot of the dependencies and handle things in more flexible ways as I can, I'm hoping that this will help to solve this issue.

**Comment by travenasty** [comment] 2016-08-23 00:09
@TylorS Thanks for being so responsive.  I really appreciate your efforts to provide such useful solutions to the open-source community.  I am attaching a few more screenshots of what the experience is like on my machine.

<img width="582" alt="screen shot 2016-08-22 at 5 55 58 pm" src="https://cloud.githubusercontent.com/assets/370488/17875801/63fdcf0a-6892-11e6-8c79-4bca0b3a6d54.png">

As an inexperienced user, I tried to execute a commit without adding any files.  You notice the repetitive blank-line output at first, and then the un-handled exception caused by my lack of pending git additions.

<img width="584" alt="screen shot 2016-08-22 at 5 57 59 pm" src="https://cloud.githubusercontent.com/assets/370488/17875811/6c51c882-6892-11e6-9d44-5c2e391ab985.png">

After adding LICENSE.md and trying the commit again, you see that you can make it through all of the appropriate prompts (albeit trippled), but when it tries to actually do the git commit, it fails. 

I don't mean to tack on additional issues on this thread, but they are one in the same to me and I look forward to the updates you are making.  👍   Let me know if you need me to test anything else, and keep up the good work!

**Comment by TylorS** [comment] 2016-08-23 01:12
Thank you for the additional information, it is useful. I've solved `the un-handled exception caused by my lack of pending git additions` already tonight with my current work. I've rewritten everything to be much more custom solutions, which allows for more polish around things I previously had no say over, and slims down on dependencies. 

Another nice side-effect is that it opens up a public API to building other tools on top of Northbrook, which I'd suspect would be mostly useful for providing more 'defaults' out-of-the-box, and probably many things I've not thought of.

Thank you for your kind words, I hope this project to be useful for many people. I'm very serious about this one, and want to see it succeed, so I appreciate you trying it out so early on. It's too easy to be 'good enough' when its just me using it.

**Comment by TylorS** [comment] 2016-08-23 09:13
Hey @travenasty If you would be so kind to test out `v2.0.1` and let me know how things work for you :)

**Comment by travenasty** [comment] 2016-08-23 14:34
<img width="255" alt="screen shot 2016-08-23 at 8 30 48 am" src="https://cloud.githubusercontent.com/assets/370488/17895994/3984eb58-690c-11e6-9be8-ecd94997d2fa.png">

```
npm i -g northbrook
...
```

<img width="780" alt="screen shot 2016-08-23 at 8 31 20 am" src="https://cloud.githubusercontent.com/assets/370488/17896001/3ecf3d7a-690c-11e6-8cc7-97a4b82f9732.png">

And it throws the same 'plugins' of null, on the nb init command as well.

**Comment by TylorS** [comment] 2016-08-24 13:31
The new errors are resolved in the latest version 2.0.14 as of writing this. I know I'm getting closer :)

Just as an FYI, so many releases occurred because I was trying to setup automatic releasing with Travis CI, but haven't found the right configurations yet.

**Comment by travenasty** [comment] 2016-08-25 03:00
Cool! I have installed the latest published version 2.0.20, and so far I haven't had any issues (other than just not fully grasping the entire flow of managing the repo dependencies)

However, the prompts are nice and clean.  no more duplicated/empty output, and I havent hit any exceptions.  :D  Nice work!  I'd say this issue can be closed.

**Comment by TylorS** [comment] 2016-08-25 03:39
Thank you @travenasty for testing it out. Feel free to reach out to me here if you run into any more trouble :)

**Closed as completed by TylorS** 2016-08-25 03:39 UTC
Labels: Type: Bug, Weight: 4 - Must

**Comment by TylorS** [comment] 2016-08-25 03:40
Also as another note, I do have automatic deployments working properly :)
Anytime things are pushed to master it pumps out a new release!
